openapi: 3.0.0
servers:
  - url: 'http://jagannath.pdn.cam.ac.uk:31337'
    variables: {}
info:
  title: LODVectors API
  description: >-
    The LODVectors API focuses on computation involving knowledge graph
    embeddings.
  version: 0.1.0
  termsOfService: >-
    https://github.com/bio-ontology-research-group/lodvectors/blob/master/apidocs/termsofservice.md
  contact:
    email: robert.hoehndorf@kaust.edu.sa
    name: Robert Hoehndorf
    x-role: responsible developer
    url: 'https://www.kaust.edu.sa/en/study/faculty/robert-hoehndorf'
  x-contacts:
    name: Michel Dumontier
    x-role: documentation editor
    url: 'http://dumontierlab.com'
    email: michel.dumontier@maastrichtuniversity.nl
tags: []
paths:
  /tsne.groovy:
    get:
      summary: >-
        Perform a SPARQL query on the server enhanced with vector
        representations.
      description: >-
        Queries the UniProt SPARQL endpoint and for each URI it can matches, it
        injects x and y coordinates of a vector representation using an t-SNE
        transformation. New fields are added with the suffix "_coord_x" and
        "_coord_y". 
      operationId: query
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: A valid SPARQL query
          allowEmptyValue: true
          examples:
            sparql:
              $ref: >-
                https://raw.githubusercontent.com/bio-ontology-research-group/lodvectors/master/apidocs/api_query_example.sparql
      responses:
        '200':
          description: Description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                sparql:
                  externalValue: >-
                    https://raw.githubusercontent.com/bio-ontology-research-group/lodvectors/master/apidocs/api_query_response.json
        '405':
          description: Server error
      security: []
  /sim.groovy:
    get:
      summary: Allows retrieval and similarity-based search of LODVectors.
      description: >-
        The API allows retrieval of vector representations of resources in JSON
        format, and also performs similarity-based retrieval (using cosine
        similarity) of related resources, given a resource.
      operationId: type
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum:
              - getvec
              - sim
          description: >-
            One of two keywords determining which operation to perform. "getvec"
            will retrieve vectors, while "sim" will find the ten most similar
            vectors.
          allowEmptyValue: false
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: >-
            The URL of the resource which should be queried. Depending on the
            type of the query, will either return the vector representation of
            the resource or the 10 most similar resources together with their
            cosine similarity values.
          allowEmptyValue: false
        - name: smart
          in: query
          required: false
          schema:
            type: boolean
          description: Whether to return SmartAPI metadata in the query. Defaults to false.
          allowEmptyValue: false
      responses:
        '200':
          description: >-
            Will either return the vector representation of the resource or the
            ten most similar vectors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
              examples:
                sparql:
                  externalValue: >-
                    https://raw.githubusercontent.com/bio-ontology-research-group/lodvectors/master/apidocs/api_sim_response_example.json
        '405':
          description: Server error
      security: []
externalDocs:
  description: ''
  url: 'https://github.com/dbcls/bh17/wiki/LODVectors'
components:
  schemas:
    response:
      type: object
      properties:
        meta:
          type: object
          properties:
            '@context':
              type: string
              format: url
            'smartapi:urlCalled':
              type: string
              format: url
            'prov:generatedAt':
              type: string
              format: dateTime
            'prov:wasGeneratedBy':
              type: string
              format: url
            'smartapi:errors':
              type: array
              items:
                type: string
            'smartapi:warnings':
              type: array
              items:
                type: string
            'smartapi:resultCount':
              type: integer
        results:
          type: array
          items:
            type: object
  responses: {}
  parameters: {}
  examples: {}
  securitySchemes: {}
  headers: {}
  links: {}
  callbacks: {}
security: []
